---
- name: k3s | download binary
  get_url:
    url: "{{ k3s_bin_url }}"
    dest: /usr/local/bin/k3s
    group: adm
    mode: 0750
  notify: restart k3s

- name: k3s | softlink kubectl
  file:
    src: k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: k3s | bash completion package
  package:
    name: bash-completion

- name: k3s | bash completion
  shell:
    cmd: /usr/local/bin/kubectl completion bash > /etc/bash_completion.d/kubectl
    creates: /etc/bash_completion.d/kubectl

- name: k3s | enable forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: k3s | dirs
  file:
    path: "{{ item | dirname }}"
    state: directory
  loop:
  - "{{ k3s_iptables_conf }}"
  - "{{ k3s_config_file }}"

- name: k3s | config
  template:
    src: config.yaml.j2
    dest: "{{ k3s_config_file }}"
    group: adm
    mode: 0640
  notify:
  - restart k3s

- name: k3s | systemd service
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dst }}"
  loop:
  - src: k3s.service
    dst: /etc/systemd/system/k3s.service
  - src: iptables.conf
    dst: "{{ k3s_iptables_conf }}"
  notify:
  - daemon-reload
  - restart k3s

- name: k3s | enable service
  service:
    name: k3s
    state: started
    enabled: yes

- include_tasks: save_token.yml
  when: k3s_token is not defined

