---
- name: k3s | fetch install script
  get_url:
    url: "{{ k3s_install_url }}"
    dest: /usr/local/bin/k3s
    mode: '0755'

- name: k3s | sysctl 
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: k3s | server | kernel modules
  modprobe:
    name:
      - br_netfilter
      - overlay
  when: k3s_servers in group_names

- name: k3s | systemd unit
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  loop:
    - k3s.service
    - k3s.service.env

- name: k3s | systemd service
  service:
    name: k3s
    state: started
    enabled: yes

- name: k3s | server | get token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_reg
  when: k3s_servers in group_names

- name: k3s | server | save token
  set_fact:
    k3s_token: "{{ k3s_token_reg.content }}"
  when: k3s_servers in group_names

- name: k3s | node | store token
  template:
    src: node-token.j2
    dest: /var/lib/rancher/k3s/server/node-token
  when: k3s_servers not in group_names

