---
- name: k3s | fetch install script
  get_url:
    url: "{{ k3s_install_url }}"
    dest: "{{ k3s_install_tmp }}"
    mode: '0755'

- name: k3s | run install script
  shell: "{{ k3s_install_tmp }}"
