---
- name: k3s | download binary
  get_url:
    url: "{{ k3s_bin_url }}"
    dest: /usr/local/bin/k3s
    mode: '0755'
  notify: restart k3s

- name: k3s | enable forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: k3s | create dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ k3s_token_file | dirname }}"
    - /etc/systemd/system/k3s.service.d

- name: k3s | systemd service
  template:
    src: "{{ item.src }}.j2"
    dest: "/etc/systemd/system/{{ item.dest | d() }}/{{ item.src }}"
  loop:
    - { src: k3s.service }
    - { src: k3s.service.env }
    - { src: iptables.conf, dest: k3s.service.d }
  notify:
    - daemon-reload
    - restart k3s

- name: k3s | enable service
  service:
    name: k3s
    state: started
    enabled: yes

- include_tasks: save_token.yml
  when: k3s_token is not defined

