---
- name: k3s | download binary
  get_url:
    url: "{{ k3s_bin_url }}"
    dest: /usr/local/bin/k3s
    mode: '0755'
  notify: restart k3s

- name: k3s | enable forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: k3s | token dir
  file:
    path: "{{ k3s_token_file | dirname }}"
    state: directory
  when: k3s_token is defined

- name: k3s | set token
  template:
    src: node-token.j2
    dest: "{{ k3s_token_file }}"
  notify: restart k3s
  when: k3s_token is defined

- name: k3s | systemd service
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  loop:
    - k3s.service
    - k3s.service.env
  notify:
    - daemon-reload
    - restart k3s

- name: k3s | enable service
  service:
    name: k3s
    state: started
    enabled: yes

- include_tasks: save_token.yml
  when: k3s_token is not defined

