---
- name: k3s | download binary
  get_url:
    url: "{{ k3s_install_url }}"
    dest: /usr/local/bin/k3s
    mode: '0755'

- name: k3s | enable forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: k3s | server | kernel modules
  modprobe:
    name:
      - br_netfilter
      - overlay
  when: k3s_servers in group_names

- name: k3s | set token
  template:
    src: node-token.j2
    dest: "{{ k3s_token_file }}"
  when: k3s_token | d

- name: k3s | systemd service
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  loop:
    - k3s.service
    - k3s.service.env

- name: k3s | enable service
  service:
    name: k3s
    state: started
    enabled: yes

- import_tasks: save_token.yml
