---
- name: k3s | save_token | read
  slurp:
    src: "{{ k3s_token_file }}"
  register: k3s_token_reg

- name: k3s | save_token | set fact
  set_fact:
    k3s_token: "{{ k3s_token_reg.content | b64decode | trim }}"
    cacheable: yes

- name: k3s | save_token | group_vars dir
  become: false
  local_action:
    module: file
    path: "{{ k3s_token_varfile | dirname }}"
    state: directory

- name: k3s | save_token | group var
  become: false
  local_action:
    module: template
    src: k3s_token.yml.j2
    dest: "{{ k3s_token_varfile }}"
    mode: "0640"
